"""LLM Profile 配置的持久化接口。

UI 里可以加多套配置,挑一个 active。配置存 SQLite,API key 留意要加密
(M0 暂存明文,后续加 Fernet 之类)。
"""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.models import LlmProfile


class LlmProfileRepository(Protocol):
    async def list(self) -> list[LlmProfile]: ...
    async def get(self, profile_id: str) -> LlmProfile | None: ...
    async def upsert(self, profile: LlmProfile) -> LlmProfile: ...
    async def delete(self, profile_id: str) -> None: ...
    async def get_active(self) -> LlmProfile | None: ...
    async def set_active(self, profile_id: str) -> None: ...
    async def mark_verified(self, profile_id: str, when: datetime) -> None: ...
