"""项目 / 章节 / 角色 / 世界观的持久化接口。"""
from __future__ import annotations

from typing import Protocol

from app.domain.models import Chapter, Character, Project, WorldEntry


class ProjectRepository(Protocol):
    # ---- Project ----
    async def create_project(self, project: Project) -> Project: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(self) -> list[Project]: ...
    async def update_project(self, project: Project) -> Project: ...
    async def delete_project(self, project_id: str) -> None: ...

    # ---- Chapter ----
    async def list_chapters(self, project_id: str) -> list[Chapter]: ...
    async def get_chapter(self, chapter_id: str) -> Chapter | None: ...
    async def create_chapter(self, chapter: Chapter) -> Chapter: ...
    async def update_chapter(self, chapter: Chapter) -> Chapter: ...
    async def delete_chapter(self, chapter_id: str) -> None: ...
    async def reorder_chapters(self, project_id: str, ordered_ids: list[str]) -> None: ...

    # ---- Character ----
    async def list_characters(self, project_id: str) -> list[Character]: ...
    async def get_character(self, character_id: str) -> Character | None: ...
    async def upsert_character(self, character: Character) -> Character: ...
    async def delete_character(self, character_id: str) -> None: ...

    # ---- WorldEntry ----
    async def list_world_entries(self, project_id: str) -> list[WorldEntry]: ...
    async def get_world_entry(self, entry_id: str) -> WorldEntry | None: ...
    async def upsert_world_entry(self, entry: WorldEntry) -> WorldEntry: ...
    async def delete_world_entry(self, entry_id: str) -> None: ...
